### ISSUE TITLE
Levin Integration

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/OscillatoryIntegrals.jl#1]
Isn't the Keller method just a special case of Levin integration?

https://github.com/chebfun/examples/blob/master/quad/LevinIntegrate.m

**Comment by dlfivefifty** [comment]
Levin is missing a bc.  This makes the problem I'll-posed,  though the collocation matrix is not, and it will be well-conditioned for large w.

I think general g can be handled using the same bc as Kellers with the levin ODE 

u' + iw g' u = f

Provided g' doesn't vanish.  I did work on what to do when g' vanishes but that takes a bit more effort.
