### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by nignatiadis** [JuliaApproximation/OscillatoryIntegrals.jl#3]
Hi!

Is there any chance this package could be registered? It is very useful!

Cheers,
Nikos

**Comment by dlfivefifty** [comment]
Sure but first need to add Project.toml, testing etc. If you add this as a PR it would help

**Comment by nignatiadis** [comment]
Thanks, sounds good!

**Comment by dlfivefifty** [comment]
It was registered a while ago..
