### ISSUE TITLE
(Question) Integrands with general imaginary exponents

### ISSUE THREAD

**Issue by DanielVandH** [JuliaApproximation/OscillatoryIntegrals.jl#7]
Can this package be used for evaluating integrals of the form `integral(f(x)exp(iwg(x)), x, a, b)`, where `a` and `b` may be +/- Inf (respectively)? Based on the documentation it seems like only the case g(x) = x is supported. Is a change of variables necessary?

The integrals that I'm interested in look like the above case with a = -Inf and b = Inf with g(x) being a reasonably complicated function (e.g. it could have stationary points).

**Comment by dlfivefifty** [comment]
Not yet.

**Comment by DanielVandH** [comment]
Thanks. Are there any plans currently to implement methods for such integrands?

Also, since posting this question I've realised an appropriate form for the integral I'm interested in that conforms to exp(iwx): 
![image](https://user-images.githubusercontent.com/95613936/151153145-d4365f87-2d85-4a81-b219-fa85dba21d0a.png)
(nu and t are small, y > 1, z = x + iy). Is there any documentation online, e.g. presentations, to help with selecting the optimal space from ApproxFun to use with this package for approximating such an integral? It's not immediately clear to me based on ApproxFun/this package's documentation at least. (Apologies if you'd prefer I open a separate issue/email for this last question; I can if you prefer.) Thanks in advance.

**Comment by dlfivefifty** [comment]
No current plans, though I did develop numerical methods for oscillatory integrals with stationary points in my phd

your example looks like weighted Hermite might work well
